from enum import Enum

class MESSAGE_CODES(Enum):
    TEXT = 0
    DISCOVERY = 1
    PING = 2

    PROPOSE_VALIDATOR = 6

    SEND_BASIC_SNAPSHOT = 10
    REQUEST_BASIC_SNAPSHOT = 11

    BOOTSTRAP_JOIN_REQUEST = 5
    BOOTSTRAP_JOIN_REQUEST_ACCEPTED = 8
    BOOTSTRAP_JOIN_REQUEST_REJECTED = 9

    JOIN_REQUEST = 21
    JOIN_REQUEST_ACCEPTED = 22
    JOIN_REQUEST_REJECTED = 23

    NEW_BLOCK_ADDED = 13
    CONNECTION_DISCOVERY = 14
    NODE_DISCOVERY = 15
    GLOBAL_NODE_DISCOVERY = 16
    BECOME_VALIDATOR_REQUEST = 30
    BECOME_VALIDATOR_REQUEST_ACCEPTED = 31
    PROPOSAL = 99
    REQUEST_FULL_BLOCKCHAIN = 100
    SEND_FULL_BLOCKCHAIN = 101
    HEARTBEAT = 210
    VOTE = 201



SNAPSHOT_OPERATIONS = [
    "ADD_VALIDATOR",
    "SET_LEAD_VALIDATOR",
    "ADD_CANDIDATE",
    "ADD_VOTE",
    "ADD_ELECTOR",
]

VERIFCATION_EXEMPT_CODES = [
        MESSAGE_CODES.BOOTSTRAP_JOIN_REQUEST.value,
        MESSAGE_CODES.BOOTSTRAP_JOIN_REQUEST_ACCEPTED.value,  
        MESSAGE_CODES.BOOTSTRAP_JOIN_REQUEST_REJECTED.value,
        MESSAGE_CODES.TEXT.value #Message_Code text should be used for debug only.
    ]


CONSENSUS_RATIO = 0.7 # 70% of validators must agree.

MAX_CONNECTION_TRIES = 5

BLOCK_PERIOD = 10

BLOCK_TIMEOUT = BLOCK_PERIOD * 3

MIN_CONNECTIONS = 3
MAX_CONNECTIONS = 10

HANSHAKE_PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArDFOGOMPsUoarYCQjhi4
ktVx6yPnh2jT22PbWyI1GZHm5u8+uthLYKrszfp/7gyG00RbazyLdMcX9i0kW/GV
Up7doXqRbZuiitI0vSXskDwincDcdZ5z9+lpKE2lKxPAPswG7ANWNvTlKyc7kHSF
co/Cm3BHZPvh1rK/SvCaCpc0TpjVc/JL8PLDRyW++JiRPUauenatkIcDzxmoOakB
B3JZuaOJVr//FPDrb7oCCz1MRBXCbS3V6kiK6Vz3EJynUjDp2NRpdHBITCCh11TN
5/T4ux3EDWWyPNIxjrlPfdl32wbfOK22fOgi3+syJzQmZVU6gX9GDrwY2YYLLkpX
ywIDAQAB
-----END PUBLIC KEY-----"""

# This should be kept secret in future only stored on validator nodes.
HANSHAKE_PRIVATE_KEY = """-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEArDFOGOMPsUoarYCQjhi4ktVx6yPnh2jT22PbWyI1GZHm5u8+
uthLYKrszfp/7gyG00RbazyLdMcX9i0kW/GVUp7doXqRbZuiitI0vSXskDwincDc
dZ5z9+lpKE2lKxPAPswG7ANWNvTlKyc7kHSFco/Cm3BHZPvh1rK/SvCaCpc0TpjV
c/JL8PLDRyW++JiRPUauenatkIcDzxmoOakBB3JZuaOJVr//FPDrb7oCCz1MRBXC
bS3V6kiK6Vz3EJynUjDp2NRpdHBITCCh11TN5/T4ux3EDWWyPNIxjrlPfdl32wbf
OK22fOgi3+syJzQmZVU6gX9GDrwY2YYLLkpXywIDAQABAoIBAAVih1g05Z08PYhW
gG7JLCB/Z1Acr9VmvFVckpQPhkyV6Pwo2DPcpsLPpZctccm+f4rk1N0OKChPP5sV
v1DWxb4vNKwjmp+sYdFokHin0nWSQ9zeFqbg/SxwErdNclBeDkGIfODtm8kdMHuA
fxbd5fx2rXXR9ZGdZOsjbOMJki+pjK1sLOCbDSSwVAR5jGCtZ4mC29Qj1o3tqMPm
Jr+NJp5aOIzsEtBLYpl90hHewjlBB5RCLlQWqie/XuM8dDPTTxU9MBX1AB1QCLE6
r3z0/DQvn45JR+a6Im3z1I1/OtVPrQDP1vL08Gv8q943nbGqtNcviMkmmSSq1cRx
KIL9/7UCgYEA5ORfQki06AYtyLN/1FSM83q3qzEbGHeUUQ4Hh26J+DroezwCv7Wi
+wvuHJ2OyogbSg+AS3J9FVD6FIrtmCihpY7o4IneNfDPTKP/o/Jy828Ylf9jkBl2
USWumNtUdlMsySnPLwLzs8wgTHpQXRie4BNn6HNZuX1ibsSRy+FyyCUCgYEAwJXm
GTkdEgJxc6NA4k5ippObJiLddoYnYq44VOrcT98bhkmWk/9k+e7aRHYB/D3W5aC4
3Y7VMfbcF3zOvv0GsoCb3zI41Lthx1mDpHEYaxhEB4+3rmy3lopVryS2j0c3CrBc
4OMdE//mBWBcU53Nm4VnrAdaiTl61fPc1SvtZS8CgYBf42ggvZLD7Oq7PK9dhToz
OgK9vemq+1VwC1+OFfnIuuzvy3kfVPl9EEdlR4AtSo2cHhhSAxlxl6Xce0MDzmnB
kLfwcPFdSY+efMm4pfYQE0eKdx3/nRsa7Z1SPfgJRdjqQRChkiwD84zIXSlTht/v
4VFTaRd6hJN68fBeKAlM3QKBgCc8YuywniOVK9gLYqS4o5CccfeLEuOa4VtRc1iZ
oNkE826gf3UXi1MAPqfEAxOI5cdSv1ckSnsreBuw6c4vbrXfTeJjMQDmTD15F0Dh
acAn6XRA64M10xFwjZRpPmhicexTkhifLMVuVUazIxxGAiW1QDHkLaXXeBcu38bu
dCcxAoGAD+WBQtFk3C5c+F1nWPIMFjLNhbT+OtoTfhqKTaWomwsXhg9Lfo1ycbkF
ms32PA3SEyzwF1cmfnpuHvKMnGC7n9vuozajLpQbRgXwVPNDNLKEjfvCC+M9PzoK
Xnye9KP5nin2RVKgr2TV2FRTkmnXepGgn9XzbLP65tsWv2lamto=
-----END RSA PRIVATE KEY-----"""
