from enum import Enum

class LOG_EVENTS(Enum):

    #Info tags
    SERVER_STARTED = "SERVER_STARTED"
    CONNECTION_ESTABLISHED = "CONNECTION_ESTABLISHED"
    VOTE_COUNTED = "VOTE_COUNTED"
    CANDIDATE_ADDED = "CANDIDATE_ADDED"
    ELECTORS_LOADED = "ELECTORS_LOADED"
    MESSAGE_RECIEVED = "MESSAGE_RECIEVED"
    SNAPSHOT_UPDATED = "SNAPSHOT_UPDATED"
    SELF_BECAME_VALIDATOR = "NODE_BECAME_VALIDATOR"
    OWN_VOTE_DETECTED = "OWN_VOTE_DETECTED"
    VALIDATOR_ADDED_TO_LOCAL_SNAPSHOT = "VALIDATOR_ADDED_TO_LOCAL_SNAPSHOT"
    LEAD_VALIDATOR_CHANGED_ON_LOCAL_SNAPSHOT = "LEAD_VALIDATOR_CHANGED_ON_LOCAL_SNAPSHOT"
    SELF_BECAME_LEAD_VALIDATOR = "SELF_BECAME_LEAD_VALIDATOR"
    SUBMIT_BLOCK_TRANSACTION_INVALID = "SUBMIT_BLOCK_TRANSACTION_INVALID"

    RECEIVED_FULL_MESSAGE = "RECEIVED_FULL_MESSAGE"

    #WARN
    RECEIVED_VOTE_FAILED_VERIFCATION = "RECEIVED_VOTE_FAILED_VERIFCATION"
    ELECTOR_ALREADY_VOTED = "ELECTOR_ALREADY_VOTED"
    UNKNOWN_ELECTOR_CREDS = "UNKNOWN_ELECTOR_CREDS"
    SIG_NOT_VALID = "SIG_NOT_VALID"
    CANDIDATE_CHOSEN_NOT_VALID = "CANDIDATE_CHOSEN_NOT_VALID"

    #ERROR
    